name: "Bitácora digital Tareas Generales "
description: "Tareas generales sobre trabajos "
body:
- type: input
  id: serie
  attributes:
    label: Usuario
    description: "Ingresar el número de serie"
    placeholder: "serial no"
  validations:
    required: true  
- type: input
  id: prevalence
  attributes:
    label: Origen de equipo a revisar
    description: "Descripción de su area de adscripción"
    placeholder: "Zona, region o área"
  validations:
    required: true
- type: input
  id: modelo
  attributes:
    label: Marca / modelo
    description: "Ingrese la marca y modelo del equipo"
    placeholder: "Epson 211, Xerox, HP 1200 , etc"
  validations:
    required: true
- type: input
  id: usuario
  attributes:
    label: Nombre de usuario 
    description: "Nombre de persona que entrega el equipo"
    placeholder: "Ingrese también numero de celular o no extensión telefonica "
  validations:
    required: true
- type: checkboxes
  id: p1
  attributes:
    label: Que problema esta presentando el equipo?
    description: Si es necesario seleccionar mas de uno
    options:
      - label: Ruido fuerte en el interior de equipo
      - label: Mala calidad de imagen
      - label: Atoramiento de papel en el recorrido / 
- type: input
  id: usuario2
  attributes:
    label: Información Adicional 
    description: "Algúna información o nota respecto al equipo"
    placeholder: "Se reemplazo toner nuevo y no funciona, viene de otra reparación, se trabajo sin tinta este equipo, "
  validations:
    required: true



